# Incluir apenas o conte√∫do em en
include:
  - en
  - swagger-ui

# Excluir os demais idiomas e o redirecioamento
exclude:
  - pt-br
  - es
  - index.html

# Permalinks simples
defaults:
  - scope:
      path: "en"
      type: "pages"
    values:
      layout: default
