# Incluir apenas o conte√∫do em espanhol
include:
  - es

# Excluir os demais idiomas e o redirecionamento
exclude:
  - pt-br
  - en
  - index.html

# Permalinks simples
defaults:
  - scope:
      path: "es"
      type: "pages"
    values:
      layout: default
      